const DIRECTORY = 'DIR'
const TRIPLIFY_SELECTION = 'TRIPLIFY_SELECTION'
const TRIPLIFY_FOCUS = 'TRIPLIFY_FOCUS'

const LOG = 'LOG'
const RETRIEVE_CONTENTS = 'RETRIEVE_CONTENTS'
export { LOG, DIRECTORY, TRIPLIFY_FOCUS, TRIPLIFY_SELECTION, RETRIEVE_CONTENTS }
