const DIRECTORY = 'DIR'
const TRIPLIFY_SELECTION = 'TRIPLIFY_SELECTION'
const TRIPLIFY_FOCUS = 'TRIPLIFY_FOCUS'
const FOCUS_CONTENT = 'FOCUS_CONTENT'

export {
  DIRECTORY,
  TRIPLIFY_FOCUS,
  TRIPLIFY_SELECTION,
  FOCUS_CONTENT,
}
