const DIRECTORY = 'DIR'
const DIRECTORY_ERROR = 'DIRECTORY_ERROR'
const TRIPLIFY = 'TRIPLIFY'
const TRIPLIFY_ERROR = 'TRIPLIFY_ERROR'
const RETRIEVE_CONTENTS = 'RETRIEVE_CONTENTS'
const RETRIEVE_CONTENTS_ERROR = 'RETRIEVE_CONTENTS_ERROR'
export { DIRECTORY, DIRECTORY_ERROR, TRIPLIFY, TRIPLIFY_ERROR, RETRIEVE_CONTENTS, RETRIEVE_CONTENTS_ERROR }
